# Generated by Django 3.2.12 on 2022-08-04 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='old_price',
            new_name='orig_price',
        ),
    ]
