# Generated by Django 4.1 on 2022-08-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_old_price_cart_orig_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='orig_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
