# Generated by Django 3.2.12 on 2022-08-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_cart_amount_alter_cart_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
